addcandidate/urls.py
from django.urls import path
from . import views

# TEMPLATE URLS!
app_name = 'addcandidate'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
    path('addcandidate/', views.add_candidate, name='addcandidate'),
    path('add_candidate_submit', views.add_candidate_submit, name='add_candidate_submit'),
    path('candidatelist', views.list_candidate, name='listcandidate'),
    path('candidateview/<int:pk>', views.view_candidate, name='viewcandidate'),
    path('candidateupdate/<int:pk>', views.update_candidate, name='updatecandidate'),
    path('candidatedelete/', views.delete_candidate, name='deletecandidate'),
]

hrproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from addcandidate import views

urlpatterns = [
    path('', include('addcandidate.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

addcandidate/models.py
from django.contrib.messages import constants
from django.db import models
from django.db.models import constraints
from django.utils import timezone
from django.contrib.auth.models import User


class Constants:
    ROLE = (
        ('sales', 'Sales'),
        ('human_resources', 'Human Resources'),
        ('marketing', 'Marketing'),
        ('sales_and_marketing', 'Sales & Marketing'),
        ('graphic_designer', 'Graphic Designer'),
        ('operations', 'Operations'),
        ('content_writer', 'Content Writer'),
        ('digital_marketing', 'Digital Marketing'),
        ('python_developer', 'Python Developer'),
        ('android_developer', 'Android Developer'),
        ('web_developer', 'Web Developer'),
        ('administration', 'Administration'),
        ('relationship_manager', 'Relationship Manager'),
        ('marketing_communication', 'Marketing Communication'),
        ('finance', 'Finance'),
        ('other', 'Other')
    )

    POSITION = (
        ('intern', 'Intern'),
        ('executive', 'Executive'),
        ('other', 'Other')
    )

    RATING_PARAMETERS = (
        ('communication', 'Communication'),
        ('background_knowledge', 'Background / Knowledge'),
        ('willingness_interest', 'Wilingness / Interest'),
        ('confidence', 'Confidence'),
        ('skill_test', 'Skill (Test)'),
        ('skill', 'Skill'),
        ('knowledge', 'Knowledge'),
        ('creativity', 'Creativity'),
    )

    ATTITUDE = (
        ('active_listening', 'Active Listening'),
        ('genuine', 'Genuine'),
        ('optimistic', 'Optimistic'),
        ('responsive', 'Responsive'),
        ('humility', 'Humility'),
        ('attentive', 'Attentive'),
        ('honest', 'Honest'),
        ('laidback', 'Laidback'),
        ('boastful', 'Boastful'),
        ('unsure', 'Unsure'),
        ('brash', 'Brash'),
        ('disinterested', 'Disinterested'),
        ('manipulative', 'Manipulative'),
        ('informal', 'Informal')
    )

    PARAMETER_VALUES = (
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High')
    )

    SOURCE = (
        ('linkedin', 'LinkedIn'),
        ('internshala', 'Internshala'),
        ('indeed', 'Indeed'),
        ('naukri', 'Naukri'),
        ('letsintern', 'LetsIntern'),
        ('hellointern', 'HelloIntern'),
        ('employee_referral', 'Employee Referral'),
        ('times_jobs', 'Times Jobs'),
        ('college', 'College'),
        ('other', 'Other')
    )

    MEETING_STATUS = (
        ('shortlisted', 'Shortlisted'),
        ('rejected', 'Rejected'),
        ('meeting_to_be_held', 'Meeting To Be Held')
    )


# class Position(models.Model):
#     position = models.CharField(max_length=50, choices=Constants.POSITION, unique=True)

#     def __str__(self):
#         return self.get_position_display()


class ExtraMeeting(models.Model):
    extra_interview_date = models.DateField(blank=True, default=None, null=True)
    extra_interview_time = models.TimeField(blank=True, default=None, null=True)

    extra_meeting_status = models.CharField(max_length=50, choices=Constants.MEETING_STATUS, blank=True, null=True)
    additional_notes_on_extra_meeting = models.TextField(blank=True, null=True)



class Parameter(models.Model):
    parameters = models.CharField(max_length=50, choices=Constants.RATING_PARAMETERS, unique=True)
    # parameter_value = models.CharField(max_length=50, choices=Constants.PARAMETER_VALUES)

    def __str__(self):
        return self.get_parameters_display()
    

class Role(models.Model):
    role = models.CharField(max_length=50, choices=Constants.ROLE, unique=True)
    rating_parameters = models.ManyToManyField(Parameter)

    def __str__(self):
        return self.get_role_display()
    

class Attitude(models.Model):
    attitude = models.CharField(max_length=50, choices=Constants.ATTITUDE, unique=True)

    def __str__(self):
        return self.get_attitude_display()
    

#recruitment process for candidate filled by HR
class Recruitment(models.Model):
    HR = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50, blank=True, null=True)
    contact_number = models.CharField(max_length=13, unique=True)
    linkedin_link = models.URLField(max_length=200, unique=True, blank=True)
    resume = models.FileField(upload_to='resume/', blank=True, null=True)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    date_called = models.DateField(default=timezone.now)
    time_called = models.TimeField()

    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    # position = models.ForeignKey(Position, on_delete=models.CASCADE)
    position = models.CharField(max_length=50, choices=Constants.POSITION)

    other_role = models.CharField(max_length=50, blank=True)
    other_position = models.CharField(max_length=50, blank=True)


    first_param_val = models.CharField(max_length=50, choices=Constants.PARAMETER_VALUES)
    second_param_val = models.CharField(max_length=50, choices=Constants.PARAMETER_VALUES)
    third_param_val = models.CharField(max_length=50, choices=Constants.PARAMETER_VALUES)
    fourth_param_val = models.CharField(max_length=50, choices=Constants.PARAMETER_VALUES)

    attitude = models.ManyToManyField(Attitude)

    #Notes
    positive_notes = models.TextField(blank=True)
    negative_notes = models.TextField(blank=True)
    additional_notes = models.TextField(blank=True)

    #Sources
    source = models.CharField(max_length=50, choices=Constants.SOURCE)
    other_source = models.CharField(max_length=50, blank=True)

    #1st meeting status
    first_meeting_status = models.CharField(max_length=50, choices=Constants.MEETING_STATUS)
    additional_notes_on_first_meeting = models.TextField(blank=True)

    #if shortlisted then schedule interview
    interview_date = models.DateField(blank=True, default=None, null=True)
    interview_time = models.TimeField(blank=True, default=None, null=True)

    #2nd meeting status
    second_meeting_status = models.CharField(max_length=50, choices=Constants.MEETING_STATUS, blank=True, null=True)
    additional_notes_on_second_meeting = models.TextField(blank=True, null=True)

    more_meetings = models.ManyToManyField(ExtraMeeting, blank=True)

    #if shortlisted then attatch aadhar and add email 
    aadhar = models.FileField(upload_to='aadhar/', blank=True, null=True)
    email = models.EmailField(max_length=254, blank=True, null=True)












#passwords: 
#deepak - 1234
#mansi - hr@12345
#kassandra - hr@23456
#sakshi - hr@34567

addcandidate/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls.conf import include
from .models import *
from json import dumps
from django.db.models import Q, fields
from .forms import ExtraMeetingForm, RecruitmentForm
from django.forms import modelformset_factory, formset_factory


def home(request):
    return render(request, 'addcandidate/home.html')


@login_required
def add_candidate(request):
    roles = Role.objects.all()
    positions = Constants.POSITION
    sources = Constants.SOURCE
    param_values = Constants.PARAMETER_VALUES
    roles_parameters = {}
    for role in roles:
        r = Role.objects.filter(role=role.role).values_list('rating_parameters__parameters')
        r = list(i[0] for i in r)
        roles_parameters[role.role] = r

    # print(roles_parameters, roles_parameters['sales'], type(roles_parameters['sales']))
    roles_parameters = dumps(roles_parameters)

    # print(roles_parameters)
    param_no = 4
    param_val_no = 3

    attitudes = Attitude.objects.all()


    context = {
        'roles': roles,
        'positions': positions,
        'sources': sources,
        'roles_parameters': roles_parameters,
        'param_values': param_values,
        'param_no': range(param_no),
        'param_val_no': range(param_val_no),
        'attitudes': attitudes
    }
    return render(request, 'addcandidate/addcandidate.html', context)


@login_required
def list_candidate(request):
    if request.user.is_superuser:
        completed_recruitment_forms = Recruitment.objects.filter(Q(first_meeting_status="rejected")  | Q(second_meeting_status="shortlisted") | Q(second_meeting_status="rejected")).order_by('-pk')
        incompleted_recruitment_forms = Recruitment.objects.filter(~(Q(first_meeting_status="rejected")  | Q(second_meeting_status="shortlisted") | Q(second_meeting_status="rejected"))).order_by('-pk')
        all_recruitment_forms = Recruitment.objects.all().order_by('-pk')
    else:
        completed_recruitment_forms = Recruitment.objects.filter(Q(HR=request.user) & (Q(first_meeting_status="rejected")  | Q(second_meeting_status="shortlisted") | Q(second_meeting_status="rejected"))).order_by('-pk')
        incompleted_recruitment_forms = Recruitment.objects.filter(Q(HR=request.user) & ~((Q(first_meeting_status="rejected")  | Q(second_meeting_status="shortlisted") | Q(second_meeting_status="rejected")))).order_by('-pk')
        all_recruitment_forms = Recruitment.objects.filter(Q(HR=request.user)).order_by('-pk')

    print(completed_recruitment_forms)
    print(incompleted_recruitment_forms)
    print(all_recruitment_forms)


    context = {
        'completed_recruitment_forms': completed_recruitment_forms,
        'incompleted_recruitment_forms': incompleted_recruitment_forms,
        'all_recruitment_forms': all_recruitment_forms
    }

    return render(request, 'addcandidate/listcandidate.html', context)


@login_required
def view_candidate(request, pk):
    context = {}
    candidate = Recruitment.objects.get(pk=pk)
    if candidate.HR != request.user:
        return HttpResponseRedirect(reverse("addcandidate:listcandidate"))

    context["candidate"] = candidate

    return render(request, "addcandidate/viewcandidate.html", context)


@login_required
def update_candidate(request, pk):
    # context = {}
 
    # fetch the object related to passed id
    obj = get_object_or_404(Recruitment, pk = pk)
 
    # pass the object as instance in form
    form = RecruitmentForm(instance = obj)
    candidate = Recruitment.objects.get(pk=pk)
    if candidate.HR != request.user:
        return HttpResponseRedirect(reverse("addcandidate:listcandidate"))


    extra_meeting_objects = []
    extra_meeting_forms = []
    for extra_meeting in candidate.more_meetings.all():
        extra_meeting_objects.append(extra_meeting)
        extra_meeting_forms.append((ExtraMeetingForm(instance=extra_meeting)))


    last_meet_id = list(ExtraMeeting.objects.all().values_list('pk'))[-1][0]


    ExtraMeetingFormSet = modelformset_factory(ExtraMeeting, form=ExtraMeetingForm, fields='__all__', extra=0)
    formset = ExtraMeetingFormSet(queryset=candidate.more_meetings.all())

    print(formset.is_valid())


    # ExtraMeetingFormSet = formset_factory(ExtraMeetingForm)
    # formset = ExtraMeetingFormSet()
    

    
 
    # save the data from the form and
    # redirect to detail_view

    print("-------------------sdfkjhfehl--------------------------------------------", form.is_valid())
    if request.method == 'POST':
        form = RecruitmentForm(request.POST, request.FILES, instance = obj)
        formset = ExtraMeetingFormSet(request.POST, queryset=candidate.more_meetings.all())

        print(form.is_valid())
        print(formset.is_valid())
        print(formset.errors)
        print(formset.non_form_errors())
        # print(form)
        if form.is_valid() and formset.is_valid():
            inst = form.save(commit=False)
            print("hjhjhlhlohhlhlhlh")

            print(formset.is_valid())
            print(formset.errors)
            print(formset.non_form_errors())
            for data in formset:
                data.save()

            extra_meetings_in_update = ExtraMeeting.objects.filter(pk__gt=last_meet_id)
            for mt in extra_meetings_in_update:
                inst.more_meetings.add(mt)
            inst.save()
            

            
            
            return HttpResponseRedirect(reverse("addcandidate:viewcandidate", args=(pk,)))


 
    # add form dictionary to context
    roles = Role.objects.all()
    positions = Constants.POSITION
    sources = Constants.SOURCE
    param_values = Constants.PARAMETER_VALUES
    roles_parameters = {}
    for role in roles:
        r = Role.objects.filter(role=role.role).values_list('rating_parameters__parameters')
        r = list(i[0] for i in r)
        roles_parameters[role.pk] = r

    # print(roles_parameters, roles_parameters['sales'], type(roles_parameters['sales']))
    roles_parameters = dumps(roles_parameters)

    param_no = 4
    param_val_no = 3

    attitudes = Attitude.objects.all()


    context = {
        'roles': roles,
        'positions': positions,
        'sources': sources,
        'roles_parameters': roles_parameters,
        'param_values': param_values,
        'param_no': range(param_no),
        'param_val_no': range(param_val_no),
        'attitudes': attitudes,
        'form': form,
        'extra_meeting_forms': extra_meeting_forms,
        'formset': formset,
        'last_meet_id': last_meet_id
    }

 
    return render(request, "addcandidate/updatecandidate.html", context)


@login_required
def delete_candidate(request):
    if request.method == 'POST':
        candidate_id=request.POST["dlt_candidate"]
        print("candidate_id--------------------------------", candidate_id, type(candidate_id))
        candidate=Recruitment.objects.get(pk=candidate_id)
        for extra_meeting in candidate.more_meetings.all():
            extra_meeting.delete()
        candidate.delete()
    return HttpResponseRedirect(reverse("addcandidate:listcandidate"))



@login_required
def add_candidate_submit(request):
    if request.method == 'POST':
        fn = request.POST.get("first-name")
        mn = request.POST.get("middle-name")
        ln = request.POST.get("last-name")
        print(fn, mn, ln)

        contact = request.POST.get("contact-number")
        linkedin  = request.POST.get("linkedin-link")

        state = request.POST.get('input-state')
        district = request.POST.get('input-district')
        print(state, district)

        date_called = request.POST.get('date-called')
        time_called = request.POST.get('time-called')

        role = Role.objects.get(role=request.POST.get('role'))
        position = request.POST.get('position')

        other_role = request.POST.get('other-role')
        other_position = request.POST.get('other-position')

        rp1 = request.POST.get('roles-parametrs-0')
        rp2 = request.POST.get('roles-parametrs-1')
        rp3 = request.POST.get('roles-parametrs-2')
        rp4 = request.POST.get('roles-parametrs-3')
        print(rp1, rp2, rp3, rp4)

        attitudes = request.POST.getlist('attitude')
        print("hello", attitudes, type(attitudes))
        

        p_note = request.POST.get('positive-note')
        n_note = request.POST.get('negative-note')
        a_note = request.POST.get('additional-note')

        source = request.POST.get('source')
        other_source = request.POST.get('other-source')

        fm_status = request.POST.get('first-meeting-status')
        fm_a_note = request.POST.get('additional-note-first-meeting')
        print("status1", fm_status)

        interview_date = request.POST.get('date-interview')
        interview_time = request.POST.get('time-interview')

        sm_status = request.POST.get('second-meeting-status')
        sm_a_note = request.POST.get('additional-note-second-meeting')
        print("status2", sm_status)

        email = request.POST.get('email')

        candidate = Recruitment.objects.create(
            HR=request.user,
            first_name=fn,
            middle_name=mn,
            last_name=ln,
            contact_number=contact,
            linkedin_link=linkedin,
            state=state,
            city=district,
            date_called=date_called,
            time_called=time_called,
            role=role,
            position=position,
            other_role=other_role,
            other_position=other_position,
            first_param_val=rp1,
            second_param_val=rp2,
            third_param_val=rp3,
            fourth_param_val=rp4,

templates/addcandidate/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>XIRCLS!
        {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/logic.js' %}"></script>
</head>
<body>

    <div class="ui stackable massive inverted teal top attached menu" id="navbar">
        <a class="item" href="{% url 'addcandidate:home' %}">
            <i class="ui active inverted large home icon"></i>
            Home
        </a>
        {% if user.is_authenticated %}
            <div class="item">
                    Welcome: {{user.username}}
            </div>
        {% endif %}


        <div class="right inverted menu">
            {% if user.is_authenticated %}
                <a class="item" href="{% url 'addcandidate:addcandidate' %}">
                    Add Candidate
                </a>
                <a class="item" href="{% url 'addcandidate:listcandidate' %}">
                    View Candidates
                </a>
                <a class="right item" href="{% url 'addcandidate:logout' %}">
                    <i class="ui inverted sign out icon"></i>
                    Logout
                </a>
            {% else %}
                <a class="right item" href="{% url 'addcandidate:user_login' %}">
                    <i class="ui inverted sign out icon"></i>
                    Login
                </a>
            {% endif %}

        </div>
    </div>


<div class="container">

    {% block body_block %}
<!--    Anything outside of this will be inherited-->
    {% endblock %}
</div>

</body>
</html>

templates/addcandidate/viewcandidate.html
{% extends 'addcandidate/base.html' %}
{% load staticfiles %}
{% load custom_tags %}

{% block title %}View Candidate{% endblock %}

{% block body_block %}
<div class="ui stackable doubling centered card right floated"
         style="margin: auto;
                margin-top: 6%;
                min-width: 800px;">



<div class="ui form" style="padding: 8px; padding-left: 24px; padding-right: 24px; padding-bottom: 100px;">        

  <h4 class="ui dividing header">CANDIDATE VIEW
  <a href="{% url 'addcandidate:updatecandidate' pk=candidate.pk %}"><button class="ui basic button" style="margin-left:85%;">Update</button></a>
  </h4>

  <h4 class="ui horizontal divider header">
    <i class="info circle icon"></i>
    Personal Info
</h4>
  
  <div class="field">
    <div class="three fields">
        <div class="field">
        <label>First Name</label>
        {{candidate.first_name}}
        </div>
        <div class="field">
        <label>Middle Name</label>
        {% ifequal candidate.middle_name None %}
        ---------
        {% else %}
        {{candidate.middle_name}}
        {% endifequal %}
        </div>
        <div class="field">
        <label>Last Name</label>
        {% ifequal candidate.last_name None %}
        ---------
        {% else %}
        {{candidate.last_name}}
        {% endifequal %}
        </div>
    </div>
  </div>

  <div class="field">
    <label>Contact Number</label>
    <div class="six wide field">
      {{candidate.contact_number}}
    </div>
  </div>

<div class="valid-msg-error">
    <span id="link-resume-error" style="color:red">{{link_resume_error}}</span>
</div>

  <div class="field">
    <label>Linkedin Link</label>
    <div class="twelve wide field">
      <a href="{{candidate.linkedin_link}}">{{candidate.linkedin_link|truncatechars:60}}</a>
    </div>
  </div>

    <div class="field">
    <label>Resume</label>
    <div class="twelve wide field">
        <a href="..\media\{{candidate.resume}}">{{candidate.resume}}</a>
    </div>
    </div>

  
  <div class="two fields">
    <div class="field">
    <label>State</label>
      {{candidate.state}}
    </div>

    <div class="field">
    <label>City</label>
        {{candidate.city}}
    </div>
  </div>

        <h4 class="ui horizontal divider header">
            <i class="phone icon"></i>
            Called On
        </h4>

        <div class="two fields">
            <div class="eight wide field">
                <label>Date</label>
                {{candidate.date_called}}
           </div>
            <div class="eight wide field">
                <label>Time</label>
                {{candidate.time_called}}
           </div>
        </div>

        {% comment %} <input type="hidden" id="canvasText" name="canvasText" value="" /> {% endcomment %}
        
        <h4 class="ui horizontal divider header">
            <i class="tag icon"></i>
            Applied For
        </h4>

        <div class="field">
            <div class="two fields">
                <div class="eight wide field">
                    <label>Role</label>
                    {% ifequal candidate.role.role "other"  %}
                        {{candidate.role}}-{{candidate.other_role}}
                    {% else %}
                        {{candidate.role}}
                    {% endifequal %}
                </div>
                <div class="eight wide field">
                    <label>Position</label>
                    {% ifequal candidate.position "other"  %}
                        {{candidate.get_position_display}}-{{candidate.other_position}}
                    {% else %}
                        {{candidate.get_position_display}}
                    {% endifequal %}
                </div>
            </div>
        </div>


        <h4 class="ui horizontal divider header">
            <i class="star outline icon"></i>
            Rating
        </h4>


        <div class="ten wide field" id="rating-parameters">
        <label>Parameters</label>
            <table class="ui definition table">       
                {% for rl in candidate.role.rating_parameters.all %}
                {% comment %} <div class="field">
                    {{rl.get_parameters_display}} :  {{candidate|get_param_val:forloop.counter}}
                </div> {% endcomment %}
                <tr>
                    <td class="eight wide column">{{rl.get_parameters_display}}</td>
                    <td>{{candidate|get_param_val:forloop.counter}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>

        <div class="twelve wide field">
            <label>Attitude</label>

            {% for at in candidate.attitude.all %}
                {{at.get_attitude_display}}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
            {% endfor %}
        </div>

        <br>
        <br>

        <h4 class="ui horizontal divider header">
            <i class="align left icon"></i>
            Notes
        </h4>

        <div class="field">
            <div class="field">
                <label>Positive</label>
                <div style="margin-left: 34px;">
                {{candidate.positive_notes}}
                </div>
            </div>
            <div class="field">
                <label>Negative</label>
                <div style="margin-left: 34px;">
                {{candidate.negative_notes}}
                </div>
            </div>
            <div class="field">
                <label>Additional</label>
                <div style="margin-left: 34px;">
                {{candidate.additional_notes}}
                </div>
            </div>
        </div>

        <br>
        <br>

        <h4 class="ui horizontal divider header">
            <i class="tag icon"></i>
            Source
        </h4>



        <div class="field">
            <label>Source</label>
            <div class="twelve wide field">
                {% ifequal candidate.source "other"  %}
                    {{candidate.get_source_display}}-{{candidate.other_source}}
                {% else %}
                    {{candidate.get_source_display}}
                {% endifequal %}
            </div>
        </div>

        <br>


        <h4 class="ui horizontal divider header">
            <i class="paper plane outline icon"></i>
            1st Meeting
        </h4>


        <div class="field">
            <div class="twelve wide fields" style="padding-left: 8px;">
                <label>Status:</label>
                <div class="field">
                    {{candidate.get_first_meeting_status_display}}
                </div>
            </div>

            <div class="twelve wide field">
                <label>Additional Note</label>
                <div class="field" style="padding-left: 34px;">
                    {% ifequal candidate.additional_notes_on_first_meeting ""  %}
                        ----------
                    {% else %}
                        {{candidate.additional_notes_on_first_meeting}}
                    {% endifequal %}
                </div>
            </div>
        </div>

        <br>

        <h5 class="ui horizontal divider header">
            <i class="calendar check outline icon"></i>
            Scheduled Interview For 2nd Meeting
        </h5>


        <div class="field" id="schedule-interview">
            {% ifequal candidate.first_meeting_status "shortlisted" %}
                <div class="two fields">
                    <div class="eight wide field">
                        <label>Date</label>
                        {{candidate.interview_date}}
                    </div>
                    <div class="eight wide field">
                        <label>Time</label>
                        {{candidate.interview_time}}
                    </div>
                </div>
            {% else %}
                <p>Interview Not Scheduled</p>
            {% endifequal %}
        </div>

        <br>

        <h4 class="ui horizontal divider header">
            <i class="paper plane outline icon"></i>
            2nd Meeting
        </h4>


        <div class="field" id="second-meeting">
            {% ifequal candidate.first_meeting_status "shortlisted" %}
            <div class="twelve wide fields" style="padding-left: 8px;">
                <label>Status:</label>
                <div class="field">
                    {{candidate.get_second_meeting_status_display}}
                </div>
            </div>

            <div class="twelve wide field">
                <label>Additional Note</label>
                <div class="field" style="padding-left: 34px;">
                    {% ifequal candidate.additional_notes_on_second_meeting ""  %}
                        ----------
                    {% else %}
                        {{candidate.additional_notes_on_second_meeting}}
                    {% endifequal %}
                </div>
            </div>
            {% else %}
                <p>Not Shortlisted in 1st Interview</p>
            {% endifequal %}
        </div>


        {% comment %} TODO: Additional Meetings View {% endcomment %}
        {% for additional_meeting in candidate.more_meetings.all %}


            <h5 class="ui horizontal divider header">
                <i class="calendar check outline icon"></i>
                Scheduled Interview For {{forloop.counter|get_meeting_no}} Meeting
            </h5>


            <div class="field" id="schedule-interview-{{forloop.counter|get_meeting_no}}">
                    <div class="two fields">
                        <div class="eight wide field">
                            <label>Date</label>
                            {{additional_meeting.extra_interview_date}}
                        </div>
                        <div class="eight wide field">
                            <label>Time</label>
                            {{additional_meeting.extra_interview_time}}
                        </div>
                    </div>
            </div>

            <br>

            <h4 class="ui horizontal divider header">
                <i class="paper plane outline icon"></i>
                {{forloop.counter|get_meeting_no}} Meeting
            </h4>


            <div class="field" id="second-meeting">
                <div class="twelve wide fields" style="padding-left: 8px;">
                    <label>Status:</label>
                    <div class="field">
                        {{additional_meeting.get_extra_meeting_status_display}}
                    </div>
                </div>

                <div class="twelve wide field">
                    <label>Additional Note</label>
                    <div class="field" style="padding-left: 34px;">
                        {% ifequal additional_meeting.additional_notes_on_extra_meeting ""  %}
                            ----------
                        {% else %}
                            {{additional_meeting.additional_notes_on_extra_meeting}}
                        {% endifequal %}
                    </div>
                </div>
            </div>
        
        {% endfor %}


        <h4 class="ui horizontal divider header">
            <i class="file alternate outline icon"></i>
            Aadhar Attatchment & Email
        </h4>

        <div class="field" id="final-attatchment">
            <div class="field">
                {% ifequal candidate.second_meeting_status "shortlisted" %}
                    <label>Aadhar:</label>
                    <div class="twelve wide field">
                        <a href="..\media\{{candidate.aadhar}}">{{candidate.aadhar}}</a>
                    </div>
                    <label>E-mail:</label>
                    <div class="twelve wide field">
                        {{candidate.email}}
                    </div>
                {% else %}
                    <p>Not Selected in Second Interview</p>
                {% endifequal %}
            </div>
        </div>


        



</div>


    <script type="text/javascript">
            
    </script>

</div>
{% endblock %}

        